language: node_js

branches:
  only:
    - gh-pages

env:
  global:
    - URL="http://oyiptong.github.io/contentvault/ECHIDNA"
    - DECISION=""
    - secure: ""
 
script:
  - echo "ok"

after_success:
  - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
